var e="function"==typeof Object.defineProperties?Object.defineProperty:function(a,b,c){a!=Array.prototype&&a!=Object.prototype&&(a[b]=c.value)},g="undefined"!=typeof window&&window===this?this:"undefined"!=typeof global&&null!=global?global:this;function h(){h=function(){};g.Symbol||(g.Symbol=k)}var k=function(){var a=0;return function(b){return"jscomp_symbol_"+(b||"")+a++}}();
function l(){h();var a=g.Symbol.iterator;a||(a=g.Symbol.iterator=g.Symbol("iterator"));"function"!=typeof Array.prototype[a]&&e(Array.prototype,a,{configurable:!0,writable:!0,value:function(){return n(this)}});l=function(){}}function n(a){var b=0;return p(function(){return b<a.length?{done:!1,value:a[b++]}:{done:!0}})}function p(a){l();a={next:a};a[g.Symbol.iterator]=function(){return this};return a}function q(a){l();var b=a[Symbol.iterator];return b?b.call(a):n(a)}
function r(a){for(var b,c=[];!(b=a.next()).done;)c.push(b.value);return c}var t=/^(http(s)?:\/\/.)?(www\.)?[-a-zA-Z0-9@:%._\+~#=]{2,256}\.[a-z]{2,6}\b([-a-zA-Z0-9@:%_\+.~#?&//=]*)$/;function u(a){for(var b=window.location.search.substring(1).split("&"),c=0;c<b.length;c++){var d=b[c].split("=");if(d[0]==a)return d[1]}return!1};function v(a,b,c){this.url=a;this.i=b;this.f=c;this.c=document.getElementById("template-list-item").innerHTML;this.h=document.getElementById("template-list-item-edit").innerHTML;this.a=null}function w(a){a.a=document.createElement("li");a.a.classList.add("list-item");a.a.innerHTML=a.c.replace(/{{bookmark}}/g,a.url);return a.a}
v.prototype.b=function(a){"edit"===a.target.dataset.action?this.a.innerHTML=this.h.replace(/{{bookmark}}/g,this.url):"delete"===a.target.dataset.action?(this.i(this.url),this.a.removeEventListener("click",this.b)):"save"===a.target.dataset.action&&x(this,a)};
function x(a,b){b.preventDefault();var c=a.a.querySelectorAll(".error")[0],d=a.a.querySelectorAll(".input")[0];c.innerText="";d.classList.remove("input-error");var f=d.value;a.url===f?a.a.innerHTML=a.c.replace(/{{bookmark}}/g,a.url):t.test(f)?0>y.g.indexOf(f)?fetch(f,{mode:"no-cors"}).then(function(){var b=a.f;z[z.indexOf(a.url)]=f;A();B(b);a.url=f}).catch(function(){c.innerText="Please check URL exists";d.classList.add("input-error")}):(c.innerText="You have already saved this link!",d.classList.add("input-error")):
(c.innerText="Please enter a valid url",d.classList.add("input-error"))};var z=[];function C(){this.a=D.c;this.b=document.getElementById("results");this.c=new Event("updatePagination")}
function B(a){if(0<z.length){var b=document.createElement("div"),c=document.createElement("h2");c.innerText="Stored bookmarks ("+z.length+")";var d=document.createElement("ul");d.classList.add("list");for(var f=20*(a.a-1);f<20*a.a&&f<z.length;f++){var m=new v(z[f],a.f.bind(a),a);d.appendChild(w(m));m.a.addEventListener("click",m.b.bind(m))}b.appendChild(c);b.appendChild(d);a.b.replaceChild(b,a.b.firstElementChild)}else a.b.innerHTML="<p>No results to display</p>"}
C.prototype.f=function(a){z.splice(z.indexOf(a),1);A();20*(this.a-1)===z.length&&(window.location="index.html?page="+(this.a-1));B(this);document.dispatchEvent(this.c)};function A(){window.localStorage.setItem("bookmarks",JSON.stringify(z))}var y={get g(){return z}};function E(){var a=D.c;this.b=document.getElementById("pagination");this.c=1;this.a=a}function F(a,b,c){var d=document.createElement("a");d.innerText=b;d.href=a;d.classList.add.apply(d.classList,c instanceof Array?c:r(q(c)));return d}
E.prototype.f=function(){if(Math.ceil(y.g.length/20)!==this.c){this.c=Math.ceil(y.g.length/20);var a=document.createElement("nav");if(1<this.c){a.appendChild(1===this.a?F("","Previous",["prev","disabled"]):F("?page="+(this.a-1),"Previous",["prev"]));for(var b=1;b<=this.c;b++){var c=F("?page="+b,b,this.a===b?["page","active"]:["page"]);a.appendChild(c)}a.appendChild(this.a===this.c?F("","Next",["next","disabled"]):F("?page="+(this.a+1),"Next",["next"]));this.b.firstElementChild?this.b.replaceChild(a,
this.b.firstElementChild):this.b.appendChild(a)}else this.b.innerHTML=""}};function G(){this.b=(this.a=document.getElementById("form"))?this.a.querySelectorAll("input")[0]:null;this.error=this.a?this.a.querySelectorAll(".error")[0]:null;this.f=null;this.c=parseInt(u("page"),10)||1}
G.prototype.h=function(a){var b=this;a.preventDefault();var c=this.b.value;this.error.innerText="";this.b.classList.remove("input-error");t.test(c)?0>y.g.indexOf(c)?fetch(c,{mode:"no-cors"}).then(function(){z.push(c);A();b.a.removeEventListener("submit",b.h);b.a.submit()}).catch(function(){b.error.innerText="Please check URL exists";b.b.classList.add("input-error")}):(this.error.innerText="You have already saved this link!",this.b.classList.add("input-error")):(this.error.innerText="Please enter a valid url",
this.b.classList.add("input-error"))};var D=new G;if(D.a){D.f=new C;var H=D.f,I=window.localStorage.getItem("bookmarks");z=I?JSON.parse(I):[];20*(H.a-1)>z.length&&(window.location="index.html");B(H);var J=new E;J.f();document.addEventListener("updatePagination",J.f.bind(J));D.a.addEventListener("submit",D.h.bind(D))}else{var K=decodeURIComponent(u("bookmark")),L=document.getElementById("bookmark");L.innerText=K;L.href=K};
